[package]
name = "amp"
version = "0.1.0"
authors = ["Tarun Wadhwa <tarunwadhwa13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
config = "0.11.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"
log = "0.4.14"
log4rs = "1.0.0"
chrono = "0.4.19"
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "serde_json"] }
