refresh_rate: 600 seconds
appenders:
  stdout:
    kind: console
  json_log:
    kind: file
    path: "logs/app.json"
    encoder:
       kind: json
  app_log:
    kind: file
    path: "logs/app.log"
    encoder:
            pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} [{f}:{L}] {m}{n}"
  server_log:
    kind: file
    path: "logs/server.log"
    encoder:
            pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} [{M}:{L}] {m}{n}"
  access_log:
    kind: file
    path: "logs/access.log"

root:
  level: debug
  appenders:
    - stdout
loggers:
  actix_server:
    level: debug
    appenders:
      - server_log
    additive: false
  actix_web::middleware::logger:
    level: debug
    appenders:
      - access_log
    additive: false
  actix_web:
    level: debug
    appenders:
      - app_log
    additive: false
  actix_http:
    level: debug
    appenders:
      - app_log
    additive: false
  amp:
    level: debug
    appenders:
      - app_log
    additive: false
